// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXUpvxKhk_1ZcqeEGSjB_w2SyLHA1o_58',
    appId: '1:329838161268:android:1677916f62ee37b3a91021',
    messagingSenderId: '329838161268',
    projectId: 'truestep-prod',
    storageBucket: 'truestep-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiXpTYZ38mLfCx_xRKXDH6awSkEB68SEk',
    appId: '1:329838161268:ios:54801f197bb51050a91021',
    messagingSenderId: '329838161268',
    projectId: 'truestep-prod',
    storageBucket: 'truestep-prod.firebasestorage.app',
    iosBundleId: 'com.truestep.truestep',
  );

  // Web configuration - update appId after creating web app in Firebase Console
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXUpvxKhk_1ZcqeEGSjB_w2SyLHA1o_58',
    appId: '1:329838161268:web:placeholder',
    messagingSenderId: '329838161268',
    projectId: 'truestep-prod',
    authDomain: 'truestep-prod.firebaseapp.com',
    storageBucket: 'truestep-prod.firebasestorage.app',
  );
}
